### ISSUE TITLE
better usability for inverse trig functions

### ISSUE THREAD

**Issue by MattEttus** [yakir12/UnitfulAngles.jl#27]
The regular trig functions don't require code changes since you can just use the normal "sin(x)" call, for example.  However, asin, acos, etc. require a different call where units are specified.  If you just wanted the default of radians, you still need to change your code to handle it.  

It might be nice to allow asin(x) where x is Dimensionless.  That would allow the UnitfulAngles asin call to be used and return radians, thus allowing people to write code that works with or without units.

Returning Dimensionless from the regular trig functions would then allow you to call asin on sin outputs, giving you units for your output as long as you started with units.

As an aside, I was wondering why you use the "d" version of the trig functions at all.  Don't they internally convert to radians again anyway?  Would really simplify the code if you just did the calcs in radians since you're doing conversions anyway.

**Comment by yakir12** [comment]
What you are suggesting is piracy, I think. I don't think users would be happy if 
```julia
using UnitfulAngles
```
would cause all their `asin` etc to return `rad`s everywhere in their code.

> I was wondering why you use the "d" version of the trig functions at all. Don't they internally convert to radians again anyway?

No, checkout:
```julia
julia> @edit sind(45)
```
and you'll see it's more involved than that.

**Comment by cmichelenstrofer** [comment]
I gave this some thought. I agree it would be nice for the inverse functions to output radians by default if the input was somehow labeled as a `Unitful.DimensionlessQuantity`. We can differentiate between `DimensionlessQuantity` and `Number`:

```julia
julia> typeof(1rad) <: Unitful.DimensionlessQuantity
true

julia> typeof(1) <: Unitful.DimensionlessQuantity
false
```
The problem is that I don't think there's a way to have a `DimensionlessQuantity` without units. Then you would need to assign (dimensionless) units to the outputs of the regular trig functions, which is not nice.  In any case, it would only have this behavior when nesting a trig function inside its inverse function. It wouldn't be general. 

I don't think there's an easy/elegant/general way of doing this. **The current implementation is probably the best** option. If you use the inverse functions frequently you can always define unit-versions in your code, e.g.:

```julia
julia> asinr(x) = asin(rad, x)
asinr (generic function with 1 method)

julia> asinr(sin(1.35rad))
1.35 rad
```

**Comment by yakir12** [comment]
Agreed.
